### ISSUE TITLE
Hexo 博客主题个性化 | TRHX'S BLOG

### ISSUE THREAD

**Issue by TRHX** [TRHX/TRHX.github.io#13]
https://www.itrhx.com/2018/08/27/A04-Hexo-blog-topic-personalization/ 

 Hexo 博客主题的美化，添加一些实用功能，定制你的专属博客【持续更新】, 一个大学生用于自学的个人博客

**Comment by shuifengche** [comment]
哇！总结得这么棒！非常感激！

**Comment by xcsz1068** [comment]
npm WARN babel-eslint@10.0.2 requires a peer of eslint@>= 4.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ hexo-helper-live2d@3.1.1
added 287 packages from 118 contributors and audited 12910 packages in 575.305s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
 
大佬，能不能给我这个小白讲一下，为什么会这样。。。。。。

**Comment by ArLxn** [comment]
大佬我也是用的hexo-theme-material-X，能不能出一个页面卡片半透明呀？

**Comment by TRHX** [comment]
> @ArLxn
> 大佬我也是用的hexo-theme-material-X，能不能出一个页面卡片半透明呀？

在`_color.less`文件里有个卡片背景颜色改为：`@theme_cardbg: rgba(255,255,255,0.8);`
0.8就表示透明度，可以自己改

**Comment by mcmohen** [comment]
大佬问个问题，你的自定义鼠标样式我试了好像不管用，你的链接是没错的，但我复制到main.less后没有反应，我也是material-x主题

**Comment by TRHX** [comment]
> @mcmohen
> 大佬问个问题，你的自定义鼠标样式我试了好像不管用，你的链接是没错的，但我复制到main.less后没有反应，我也是material-x主题

直接写在main.less文件第二行：
```css
.l_main {
  //鼠标指针自定义
  cursor: url('https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@1.0/images/mouse.cur'),auto;
  width: ~"calc(100% - 1 * @{width_sidebar})";
  ......
  ......
```
